### ISSUE TITLE
ios send command success but not print (xprinter 350 bm)

### ISSUE THREAD

**Issue by datpt11** [HeligPfleigh/react-native-thermal-receipt-printer#119]
- [ ] I have searched the [issues](https://github.com/HeligPfleigh/react-native-thermal-receipt-printer/issues) of this repository and believe that this is not a duplicate.

**Current Behavior**

- What code are you running and what is happening?
- Include a screenshot or video if it makes sense.

**Expected Behavior**

- What do you expect should be happening?
- Include a screenshot or video if it makes sense.

**How to reproduce**

- You must provide a way to reproduce the problem.
- Explain how to run the example app and any steps that we need to take to reproduce the issue from the example app.
- Keep the repro code as simple as possible, with the minimum amount of code required to repro the issue.
- Before reporting an issue, make sure you are on latest version of the package.

**Your Environment**

| software       | version |
| -------------- | ------- |
| iOS or Android |
| react-native   |
| node           |
| npm or yarn    |

**Comment by chukiatt** [comment]
i have same issue

**Comment by PhamChuongBD** [comment]
@datpt11 bạn có xử lý case này không , giúp mình với

**Comment by hoanthan** [comment]
Hi @datpt11 
Have you resolved the issue? Can you share how?
