### ISSUE TITLE
Not able to connect to USB thermal printer

### ISSUE THREAD

**Issue by affan338** [HeligPfleigh/react-native-thermal-receipt-printer#122]
USBPrinter.connectPrinter(printer.vendorID, printer.productId).then(() => setCurrentPrinter(printer));

I'm trying to connect to a USB printer but when I'm tapping on the printer it's showing an error as mentioned below:

Attempt to invoke virtual method 'double java.lang.Double.doubleValue()' on a null object reference.

**Comment by MJahanzaibKhan** [comment]
The same issue, I'm facing.
Any solution?

**Comment by affan338** [comment]
I was using the wrong syntax, I’m able to connect now
