### ISSUE TITLE
BLUEPrinter.connect Printer does not connect printer through IOs

### ISSUE THREAD

**Issue by vilsonei** [HeligPfleigh/react-native-thermal-receipt-printer#147]
- [X] I have searched the [issues](https://github.com/HeligPfleigh/react-native-thermal-receipt-printer/issues) of this repository and believe that this is not a duplicate.

## Ask your Question
I'm developing an app for iOS, I can list the bluetooth printers by the BLEPrinter.getDeviceList method but when I call the BLEPrinter.connectPrinter method I get the error "'connectPrinter: Can't connect to printer 815DC3CD-7B45-E3FC-9C82-BD0B348CDF40'"

Could anyone give me a tip on how to solve this problem on IOs?

**Comment by vilsonei** [comment]
Sorted out! The problem was in the sequence of calls, to solve it I did the following:

1. Call BLEPrinter.getDeviceList()
2. After success call BLEPrinter.connectPrinter

See the code:

```
BLEPrinter.getDeviceList().then(devices => {
    BLEPrinter.connectPrinter(mySavedMacAddressPrinter).then(printer => {
        // In IOs the timeout was necessary for the print to be successful.
        setTimeout(() => {
             BLEPrinter.printText(txt);
         }, 1000);
     },
     (e) => {
          console.log(e);
     });
});
```

**Comment by joypatel04** [comment]
@vilsonei 

I am working on an iOS app and for some reason, I can't retrieve BLEPrinter.getDeviceList()

Did you receive the list of devices at your end?

**Comment by Rogax** [comment]
@vilsonei 
I got error `API MISUSE: <CBCentralManager: 0x112d773c0> can only accept this command while in the powered on state` when following you. Can you show me your sample code.
```javascript
bleManager.onStateChange(async state => {
        if (state === 'PoweredOn') {
          await BLEPrinter.init();
          BLEPrinter.getDeviceList().then(devices => {
            console.log('🚀 ~ devices:', devices);
            BLEPrinter.connectPrinter(item?.ipAddress).then(
              printer => {
                console.log('🚀 ~ printer:', printer);
                // In IOs the timeout was necessary for the print to be successful.
                setTimeout(() => {
                  BLEPrinter.printText('11111');
                }, 1000);
              },
              e => {
                console.log(e);
              },
            );
          });
        }
      }, true);
```
