### ISSUE TITLE
unable to resolve module 'escpos-printer-toolkit' from node_modules

### ISSUE THREAD

**Issue by DilipSutharr** [HeligPfleigh/react-native-thermal-receipt-printer#20]
Hey,
After i upgraded to v1.1.3 from v1.1.1, i am getting following error

Unable to resolve module 'escpos-printer-toolkit' from 'node_modules/react-native-thermal-receipt-printer/dist/index.js'

**Comment by HeligPfleigh** [comment]
I've removed that module in v1.1.3, you should try to install --force or remove your yarn.lock/package-lock.json then re-install again.

**Comment by DilipSutharr** [comment]
I tried what you said but still getting same error. Please help

**Comment by HeligPfleigh** [comment]
When I create a new project then add this module, I don't have any error like your. You should clear cache: 
```
watchman watch-del-all
rm -rf node_modules yarn.lock && yarn
yarn start --reset-cache
```
