### ISSUE TITLE
HTML Bill print

### ISSUE THREAD

**Issue by NextGenPosApp** [HeligPfleigh/react-native-thermal-receipt-printer#23]
How I can print HTML?

**Comment by harshmaur** [comment]
Hey @HeligPfleigh is there a way to print html?

**Comment by HeligPfleigh** [comment]
sorry, parsing html to printer is quite complicate and this library is aiming to print a simple one like text, image, etc, ... So you should do that work yourself, and there is no function directly support it in this library.
