### ISSUE TITLE
How do we issue cut command? 

### ISSUE THREAD

**Issue by harshmaur** [HeligPfleigh/react-native-thermal-receipt-printer#27]

**Comment by r3hmaanMalik** [comment]
Use this hex as cutter command.  '\x1D\x56\x01'. Tested,

**Comment by harshmaur** [comment]
Thanks @r3hmaanMalik. Does that mean I can use hex to print other characters as well? 

Also, where can I find the reference to the hex?

**Comment by r3hmaanMalik** [comment]
@harshmaur @HeligPfleigh 

Im combining ecs/pos hex commands with this module to achieve this cutter or kick draw.

Here is my code snippet

var newLine = '\x0A'; 
var cmds = esc + '!' + '\x38'
    cmds += 'ABDUL'; //text to print
    cmds += newLine; //text to print

    cmds += ''; //text to print
    cmds += newLine; // NewLine 

    cmds += esc + '!' + '\x00'; //Character font A selected (ESC ! 0)

    // cmds += 'ABCDEFGHIKLMNOPQRSTVXYZABCDEFGHIKLMNOPQRSTVXYZ'; //text to print
    cmds += 'COCA COLA';
cmds += cutter
USBPrinter.printText(cmds); 


you can use printBill or PrintText

**Comment by harshmaur** [comment]
Thanks a lot! @r3hmaanMalik 

In the research I found this https://github.com/mosquito/python-escpos/blob/master/escpos/constants.py

**Comment by r3hmaanMalik** [comment]
yes we are also this as utility.

**Comment by spyshower** [comment]
@r3hmaanMalik @harshmaur thanks guys!
