### ISSUE TITLE
Android: if there is no printer available on the defined host and port the application hangs

### ISSUE THREAD

**Issue by harshmaur** [HeligPfleigh/react-native-thermal-receipt-printer#30]
```
useEffect(() => {
    NetPrinter.init().then(() => {
      NetPrinter.connectPrinter('192.168.1.105', 9100).then(
        (printer) => console.log(printer),
        (error) => console.warn(error)
      )
    })
  }, [])
```

If there is no printer on `192.168.1.105` the whole application hangs up.

**Comment by CaioSilveira63** [comment]
i had to use React-native-ping to verify the adress before trying to connect.

`      
import Ping from 'react-native-ping';

NetPrinter.init();

const ms = await Ping.start(IPADRESS, {
        timeout: 1000,
      }).then(
        async () => {
          await NetPrinter.connectPrinter(
            IPADRESS,
            PORT,
          ),
            await NetPrinter.printBill(TEXT);
        },
        err => {
          console.log(err);
        },
`

**Comment by harshmaur** [comment]
Thanks! That should help!
