### ISSUE TITLE
Cannot read property 'Direction' of undefined

### ISSUE THREAD

**Issue by bruxalldev** [HeligPfleigh/react-native-thermal-receipt-printer#4]
Hi just tried using this for networking printing on RN0.62.1 and get this error any thoughts?

Thanks

**Comment by HeligPfleigh** [comment]
Can you describe that error more detail, such as how to reproduce that, node version you used, etc ...

**Comment by bruxalldev** [comment]
Hi 

I'm using:
"react": "16.11.0",
"react-native": "0.62.1"

Using the NetPrinter module when I load the screen I get the error even before it renders.

Do you have a fully complete example that I could use as a base?

Thanks

Rob

**Comment by HeligPfleigh** [comment]
Thanks, I'll check it

> Do you have a fully complete example that I could use as a base? 

Actually not, I'm using this for a private repo, but will have a plan to make an example soon

**Comment by bruxalldev** [comment]
Wow! thank you so much for adding the example - I'll have a play over the next few days - thank you so much!
