### ISSUE TITLE
i am not able to right align text in receipt

### ISSUE THREAD

**Issue by DilipSutharr** [HeligPfleigh/react-native-thermal-receipt-printer#5]
Hey,
this library works awesome for me but i am facing problem in right aligning the text.
Is there any tag to align the text to extreme right?
Just as we have C tag to center the text.

**Comment by HeligPfleigh** [comment]
@DilipSutharr For now this repo use [escpos-printer-toolkit](https://github.com/wanxsb/escpos-printer-toolkit) to send hex data to printer, and this one only supports those below tags
| Tags  | Description |
| ------------- | ------------- |
| C  | Center  |
| D   | Medium font |
| B   | Large font |
| QR   | QR code |

As the text alignment can be supported as mention in [this](http://www.monicacolombia.com/XP-58XX-Manual-de-programacion.pdf), I'm considering about forking that repo and add more tag in next version

| Description  | Hex code | Tag |
| ------------- | ------------- |------------- |
| Justify left  | 0  | L |
| Justify right | 2 | R |

**Comment by DilipSutharr** [comment]
That will be great, Thank you

**Comment by faisalansari97** [comment]
> @DilipSutharr For now this repo use [escpos-printer-toolkit](https://github.com/wanxsb/escpos-printer-toolkit) to send hex data to printer, and this one only supports those below tags
> 
> Tags	Description
> C	Center
> D	Medium font
> B	Large font
> QR	QR code
> As the text alignment can be supported as mention in [this](http://www.monicacolombia.com/XP-58XX-Manual-de-programacion.pdf), I'm considering about forking that repo and add more tag in next version
> 
> Description	Hex code	Tag
> Justify left	0	L
> Justify right	2	R

Does L and R tag works now?
