### ISSUE TITLE
Error when connect printer on android, ios connect normal

### ISSUE THREAD

**Issue by hoanganhnh2009** [HeligPfleigh/react-native-thermal-receipt-printer#77]
![239675292_4840639742616912_2127379729715382026_n](https://user-images.githubusercontent.com/24821246/131194294-32169313-77de-4161-b182-a4adfd8b74e0.png)

**Comment by hoanganhnh2009** [comment]
Can you help me?

**Comment by nguyen-vo** [comment]
your host is empty. That might cause the error. check seletedPrinter before passing it

**Comment by hoanganhnh2009** [comment]
> your host is empty. That might cause the error. check seletedPrinter before passing it

Tks but i used useState init
![image](https://user-images.githubusercontent.com/24821246/134098999-dba6a895-2955-490e-bba9-e3d04b6f6dd6.png)

**Comment by nguyen-vo** [comment]
I would suggest checking the selectedPrinter object. Perhaps, you can console.log it to see whether you have it before you use it. The error said you are passing a null object to the function. I would first remove the selectedPrinter?.host || "", and try it with the actual IP address " 192.168.43.100". See if it works.

**Comment by hoanganhnh2009** [comment]
> I would suggest checking the selectedPrinter object. Perhaps, you can console.log it to see whether you have it before you use it. The error said you are passing a null object to the function. I would first remove the selectedPrinter?.host || "", and try it with the actual IP address " 192.168.43.100". See if it works.
> Also I would not use selectedPrinter?.host. Rather I would check whether I actually have host and port before passing it. If I don't, I wont call the connectPrinter function

I see what you mean, I did console log and make sure host has value

**Comment by nguyen-vo** [comment]
Could you share your code where you use the NetPrinter module

**Comment by hoanganhnh2009** [comment]
import React, { useEffect, useState } from 'react';
import {
  StyleSheet,
  View,
  Text,
  Button,
  Picker,
  TextInput,
} from 'react-native';
import {
  BLEPrinter,
  NetPrinter,
  USBPrinter,
} from 'react-native-thermal-receipt-printer';
import Loader from './Loader';
import Encoder from 'esc-pos-encoder';

// - (void)sendHex:(NSString*)hex;

import { NativeModules, NativeEventEmitter, Platform } from 'react-native';
import { BufferHelper } from 'core/utils/BufferHelper';
const RNNetPrinter = NativeModules.RNNetPrinter;
import { Buffer } from 'buffer';
import moment from 'moment';
import {
  printTwoColumn,
  printFourColumn,
  printTable,
  printProduct,
} from 'core/utils/EpsonHelper';

const printerList = {
  // ble: BLEPrinter,
  net: NetPrinter,
};

export default function App() {
  const [selectedValue, setSelectedValue] = useState('net');
  const [devices, setDevices] = useState([]);
  const [loading, setLoading] = useState(false);
  const [selectedPrinter, setSelectedPrinter] = useState({
    device_name: 'Net Printer',
    host: '192.168.43.100',
    port: 9100,
    printerType: 'net',
  });

  useEffect(() => {
    const getListDevices = async () => {
      const Printer = printerList[selectedValue];
      // get list device for net printers is support scanning in local ip but not recommended
      if (selectedValue === 'net') return;
      try {
        setLoading(true);
        await Printer.init();
        const results = await Printer.getDeviceList();
        console.log('getListDevices -> results', results);
        setDevices(
          results.map((item: any) => ({ ...item, printerType: selectedValue })),
        );
      } catch (err) {
        console.warn(err);
      } finally {
        setLoading(false);
      }
    };
    getListDevices();
  }, [selectedValue]);

  const handleConnectSelectedPrinter = () => {
    if (!selectedPrinter) return;
    const connect = async () => {
      try {
        setLoading(true);
        console.log('connect -> selectedPrinter.printerType', selectedPrinter);

        switch (selectedPrinter.printerType) {
          /* case 'ble':
            await BLEPrinter.connectPrinter(
              selectedPrinter?.inner_mac_address || '',
            );
            break; */
          case 'net':
            let status = await NetPrinter.connectPrinter(
              '192.168.43.100',
              9100,
            );
            // console.log('connect -> status', status);
            break;
          default:
        }
      } catch (err) {
        console.warn(err);
      } finally {
        setLoading(false);
      }
    };
    connect();
  };

  const handlePrint = async () => {
    const encoder = new Encoder();

    let _encoder = encoder
      .initialize()
      .bold(true)
      // .size('normal')
      .align('center')
      .line('EROPI')
      .newline()
      // .size('small')
      .bold(false)
      .align('center')
      .line('348 Kim Nguu, Hai Ba Trung, Ha Noi')
      .line('0982112395')
      .newline()
      .bold(true)
      .line('HOA DON BAN HANG')
      .newline()
      .bold(false)
      .align('left')
      .line('Ngay ban: ' + moment().format('DD/MM/YYYY HH:mm:ss'))
      .line('HD: ' + 'EG36321312')
      .line(`Khach hang: Nha thuoc Huong Viet`)
      .line('-'.repeat(48));
    // loop List product
    printTable(
      _encoder,
      [
        { width: 16, align: 'left' },
        { width: 14, align: 'left' },
        { width: 6, align: 'left' },
        { width: 12, align: 'right' },
      ],
      [['Mat hang', 'Don gia', 'SL', 'T.Tien']],
    );
    printTable(
      _encoder,
      [
        { width: 26, align: 'left' },
        { width: 16, align: 'left' }, // marginRight: 2
        { width: 14, align: 'left', align: 'left' },
        { width: 6, align: 'left' },
        { width: 12, align: 'right' },
      ],
      [
        ['Thung rac nhua 240L - vang', '', '750,000', '2', '1,500,000'],
        ['Thung rac nhua 240L - Xanh', '', '7,500,000', '2', '15,500,000'],
      ],
      true,
    );

    // end list

    _encoder = _encoder.line('-'.repeat(48));
    _encoder = printTwoColumn(_encoder, 'TONG TIEN THANH TOAN:', '3,600,000');
    _encoder = printTwoColumn(_encoder, 'TONG TIEN DA GIAM:', '250,000');
    _encoder = printTwoColumn(_encoder, 'TIEN TRA LAI:', '0');
    // welcome
    _encoder = _encoder.align('center');
    _encoder = _encoder
      .line('-'.repeat(48))
      .align('center')
      .bold(true)
      .line('CAM ON QUY KHACH, HEN GAP LAI')
      .bold(false)
      .line('Website: www.abit.vn')
      // qr code
      .qrcode('https://nielsleenheer.com')
      .encode();
    //
    /* const Printer = printerList[selectedValue];
     await Printer.printText(result); */
    let options = {
      beep: true,
      cut: true,
    };
    /* let hexString = Buffer.from(_encoder).toString('hex'); //ios result like [1,2,3]
    
    RNNetPrinter.printRawData(hexString, options, function(error) {
      return console.warn(error);
    }); */
    let base64String = Buffer.from(_encoder).toString('base64'); // android
    RNNetPrinter.printRawData(base64String, function(error) {
      return console.warn(error);
    });
  };

  const handleChangePrinterType = async type => {
    setSelectedValue(prev => {
      printerList[prev].closeConn();
      return type;
    });
    setSelectedPrinter({});
  };

  const handleChangeHostAndPort = (params: string) => (text: string) =>
    setSelectedPrinter(prev => ({
      ...prev,
      device_name: 'Net Printer',
      [params]: text,
      printerType: 'net',
    }));

  const _renderNet = () => (
    <View style={{ paddingVertical: 16 }}>
      <View style={styles.rowDirection}>
        <Text>Host: </Text>
        <TextInput
          value={selectedPrinter.host}
          placeholder="192.168.100.19"
          onChangeText={handleChangeHostAndPort('host')}
        />
      </View>
      <View style={styles.rowDirection}>
        <Text>Port: </Text>
        <TextInput
          value={selectedPrinter.port + ''}
          placeholder="9100"
          onChangeText={handleChangeHostAndPort('port')}
        />
      </View>
    </View>
  );

  const _renderOther = () => (
    <Picker selectedValue={selectedPrinter} onValueChange={setSelectedPrinter}>
      {devices.map((item: any, index) => (
        <Picker.Item
          label={item.device_name}
          value={item}
          key={`printer-item-${index}`}
        />
      ))}
    </Picker>
  );

  return (
    <View style={styles.container}>
      <View style={styles.section}>
        <Text>Select printer type: </Text>
        <Picker
          selectedValue={selectedValue}
          onValueChange={handleChangePrinterType}>
          {Object.keys(printerList).map((item, index) => (
            <Picker.Item
              label={item.toUpperCase()}
              value={item}
              key={`printer-type-item-${index}`}
            />
          ))}
        </Picker>
      </View>
      <View style={styles.section}>
        <Text>Select printer: </Text>
        {selectedValue === 'net' ? _renderNet() : _renderOther()}
      </View>
      <Button
        disabled={!selectedPrinter?.device_name}
        title="Connect"
        onPress={handleConnectSelectedPrinter}
      />
      <Button
        disabled={!selectedPrinter?.device_name}
        title="Print sample"
        onPress={handlePrint}
      />
      {/* <Loader loading={loading} /> */}
    </View>
  );
}

const styles = StyleSheet.create({
  container: {
    flex: 1,
    justifyContent: 'center',
    padding: 16,
  },
  section: {
    flex: 1,
  },
  rowDirection: {
    flexDirection: 'row',
  },
});

**Comment by hoanganhnh2009** [comment]
> Could you share your code where you use the NetPrinter module

This is my code

**Comment by nguyen-vo** [comment]
I will change these line
- import { NativeModules } from 'react-native';
const RNNetPrinter = NativeModules.RNNetPrinter;

Since you already import NetPrinter from “react-native-thermal-receipt-printer”, you don't need those 2 line of code.

Secondly, you have not init the NetPrinter object.

**Comment by hoanganhnh2009** [comment]
> I will change these line
> 
> * import { NativeModules } from 'react-native';
>   const RNNetPrinter = NativeModules.RNNetPrinter;
> 
> Since you already import NetPrinter from “react-native-thermal-receipt-printer”, you don't need those 2 line of code.
> 
> Secondly, you have not init the NetPrinter object. I will add this
> 
> useEffect(()=>{
> NetPrinter.init()
> },[])

1. I import NativeModules.RNNetPrinter to use method native printRawData
2. I added useEffect(()=>{
NetPrinter.init()
},[]) but error still occurs

**Comment by nguyen-vo** [comment]
Okay, since you are using printRaw with RNNetPrinter, initialize with NetPrinter does no solve the problem. The problem is in the Native side the RNNetPrinter has not been initialize yet. So in the useEffect try RNNetPrinter.init(). I am suggesting that you look in the src/index.ts to see how they use the init function

**Comment by hoanganhnh2009** [comment]
I was able to print. Thankyou very much
