### ISSUE TITLE
RN 0.62 iOS failed to build after install this package

### ISSUE THREAD

**Issue by alanyong91** [HeligPfleigh/react-native-thermal-receipt-printer#8]
Is this package not support latest RN? `react-native-printer` last update 3 years ago, which probably is the reason failed to build.

**Comment by HeligPfleigh** [comment]
Did you follow this guide: https://github.com/HeligPfleigh/react-native-thermal-receipt-printer#troubleshoot ?

**Comment by alanyong91** [comment]
@HeligPfleigh I can't use Flipper if I disable it. Is this package going to integrate with Flipper in the future?

**Comment by HeligPfleigh** [comment]
Of course, but not in the near future, I'll do a research and fix it in my spare time.

**Comment by tr3v3r** [comment]
@HeligPfleigh Any updates here? Did you manage to resolve thos conflict?
