### ISSUE TITLE
[Unhandled promise rejection: TypeError: null is not an object (evaluating 'RNBLEPrinter.init')]

### ISSUE THREAD

**Issue by Jerry-devblog** [HeligPfleigh/react-native-thermal-receipt-printer#9]
on expo app
`    "@expo/vector-icons": "^10.0.0",
    "@react-native-community/masked-view": "0.1.10",
    "@react-navigation/bottom-tabs": "^5.6.1",
    "@react-navigation/native": "^5.6.1",
    "@react-navigation/stack": "^5.6.2",
    "expo": "~38.0.8",
    "expo-asset": "~8.1.7",
    "expo-constants": "~9.1.1",
    "expo-font": "~8.2.1",
    "expo-linking": "^1.0.1",
    "expo-splash-screen": "~0.3.1",
    "expo-status-bar": "^1.0.2",
    "expo-web-browser": "~8.3.1",
    "react": "~16.11.0",
    "react-dom": "~16.11.0",
    "react-native": "https://github.com/expo/react-native/archive/sdk-38.0.2.tar.gz",
    "react-native-gesture-handler": "~1.6.0",
    "react-native-safe-area-context": "~3.0.7",
    "react-native-screens": "~2.9.0",
    "react-native-thermal-receipt-printer": "^1.0.8",
    "react-native-web": "~0.11.7"`

``

**Comment by HeligPfleigh** [comment]
Sorry, currently this library isn't support for expo. 
As mentioned in it [document](https://docs.expo.io/workflow/using-libraries/#determining-third-party-library-compatibility), if you want to use this, you must eject your existed expo project first then follow the instruction in [README](https://github.com/HeligPfleigh/react-native-thermal-receipt-printer/blob/master/README.md)
